# Numpy Indexing and Selection

In [16]:
import numpy as np

arr = np.arange(1,20)
arr[6::2]
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

### broadcasting a value to an array

In [13]:
arr_slice = arr[1:8]
arr_slice[:] = 99
arr

array([ 1, 99, 99, 99, 99, 99, 99, 99,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [17]:
cpy_arr = arr.copy() #deep copy
cpy_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

### Arrays and dicts are passed as reference type in python 🤓

In [40]:
#arrays - reference types
arr1 = np.arange(1,10)
arr2 = arr1
arr2[8] = 100
arr1[7] = 99
print(arr1, arr2)

#String - value types
str1 = "Gabriel"
str2 = str1
str2 = "Rodrigues"
print(str1, str2)

#tuples - immutable

#dicts - reference types
dict1 = {"name":"Gabriel","surname":"Rodrigues"}
dict2 = dict1
dict2["surname"] = "Faria"
print(dict1, dict2)

[  1   2   3   4   5   6   7  99 100] [  1   2   3   4   5   6   7  99 100]
Gabriel Rodrigues
{'name': 'Gabriel', 'surname': 'Faria'} {'name': 'Gabriel', 'surname': 'Faria'}


#### Question, are standard data structures in python all classes? - Probably since it's OOP.

In [66]:
arr_2d = np.arange(1,100)
arr_2d = arr_2d.reshape(9,11)
arr_2d

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22],
       [23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66],
       [67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77],
       [78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88],
       [89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [67]:
#slicing in matrix
arr_2d[:2,1:]

array([[ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22]])

In [68]:
arr_2d[1:,:2]

array([[12, 13],
       [23, 24],
       [34, 35],
       [45, 46],
       [56, 57],
       [67, 68],
       [78, 79],
       [89, 90]])

In [74]:
arr_2d[3:6, 4:7]

array([[38, 39, 40],
       [49, 50, 51],
       [60, 61, 62]])

### Conditional Selection

In [77]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [82]:
bool_arr = arr > 5 #similar to scalar operations
bool_arr
arr[bool_arr] #Conditionally selects items where index value == true
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [83]:
arr[arr<3]

array([1, 2])

In [99]:
arr2d = np.eye(5,5)
arr2d[arr2d>0]

array([1., 1., 1., 1., 1.])

In [108]:
arr = np.arange(0,25)
arr.reshape(5,5)
arr[arr%2 == 0]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24])