# Numpy Arrays

In [1]:
import numpy as np
from numpy import random as rand

_list = [1,2,3,4]
np.array(_list)

array([1, 2, 3, 4])

In [2]:
_mat = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [3]:
# commom way of creating arrays
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [4]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [5]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [6]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [7]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [8]:
rand.rand(10,2)

array([[0.28843526, 0.15260626],
       [0.73899281, 0.51614949],
       [0.33574847, 0.10397488],
       [0.79705853, 0.1559147 ],
       [0.56920661, 0.117078  ],
       [0.5843781 , 0.41301064],
       [0.83865908, 0.43518713],
       [0.15342119, 0.37729032],
       [0.77548963, 0.85236164],
       [0.56036643, 0.69463996]])

In [9]:
rand.randn(10) #normal distribution

array([ 1.30215256,  1.27647727, -1.60081742, -1.64983925,  2.01915694,
        1.04764283,  2.11958395, -1.05821601,  0.71915891,  0.43657867])

In [10]:
rand.randint(0, 100, 10)

array([23, 94, 84, 60, 70, 88, 88, 98, 43, 32])

In [25]:
arr = np.arange(1,11)
print(arr)
arr = arr.reshape(2,5)
1/arr

[ 1  2  3  4  5  6  7  8  9 10]


array([[1.        , 0.5       , 0.33333333, 0.25      , 0.2       ],
       [0.16666667, 0.14285714, 0.125     , 0.11111111, 0.1       ]])

In [17]:
randarr = rand.randint(0,100,10)
print(randarr)
1/ randarr

[67 17  6 47 69 51 34 19 95 86]


array([0.01492537, 0.05882353, 0.16666667, 0.0212766 , 0.01449275,
       0.01960784, 0.02941176, 0.05263158, 0.01052632, 0.01162791])

In [22]:
randarr.min()
randarr.argmin()

2

In [21]:
randarr.max()
randarr.argmax()

8

In [15]:
arr.shape

(5, 10)

In [16]:
arr.dtype

dtype('int64')